name: trigger deploy pages on master
# mock remote cross-repo trigger

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["markdowns"]
    paths: ["publish/**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  trigger:
    name: Remote pages update Trigger
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ['Tyr-Wang/Tyr-Wang.github.io']
    timeout-minutes: 5
    steps:
      # require content:write
      - name: Dispatch to workflows
        run: |
            curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.PAGE_DISPATCH_TOKEN }}" \
            --request POST \
            --data '{"event_type": "content_update"}' \
            https://api.github.com/repos/${{ matrix.repo }}/dispatches  
